<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiagnosticquestionsModule1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insérer les questions du module 1 (questions 1-13)
        DB::table('diagnosticquestions')->insert([
            [
                'id' => 1,
                'titre' => 'Termines-tu ce que tu commences ?',
                'position' => '1',
                'diagnosticmodule_id' => 2,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-09-11 22:36:55',
            ],
            [
                'id' => 2,
                'titre' => 'As-tu une vision structurée pour ton activité sur au moins 3 ans ?',
                'position' => '2',
                'diagnosticmodule_id' => 2,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:27',
            ],
            [
                'id' => 3,
                'titre' => 'Quelle est ta principale motivation pour entreprendre ?',
                'position' => '3',
                'diagnosticmodule_id' => 2,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:29',
            ],
            [
                'id' => 4,
                'titre' => 'Comment planifies-tu tes semaines ?',
                'position' => '4',
                'diagnosticmodule_id' => 2,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:31',
            ],
            [
                'id' => 5,
                'titre' => 'Pour une activité nécessitant une équipe : sais-tu fédérer ou déléguer efficacement ?',
                'position' => '5',
                'diagnosticmodule_id' => 2,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:38',
            ],
            [
                'id' => 6,
                'titre' => 'Face à une critique client injuste, comment réagis-tu ?',
                'position' => '6',
                'diagnosticmodule_id' => 3,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:40',
            ],
            [
                'id' => 7,
                'titre' => 'Après un échec ou une mauvaise journée, que fais-tu ?',
                'position' => '7',
                'diagnosticmodule_id' => 3,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:42',
            ],
            [
                'id' => 8,
                'titre' => 'En situation de stress ou de colère, que fais-tu ?',
                'position' => '8',
                'diagnosticmodule_id' => 3,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:51',
            ],
            [
                'id' => 9,
                'titre' => 'Quand tu te compares aux autres entrepreneurs…',
                'position' => '9',
                'diagnosticmodule_id' => 3,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:47',
            ],
            [
                'id' => 10,
                'titre' => '1. Forces personnelles',
                'position' => '10',
                'diagnosticmodule_id' => 4,
                'diagnosticquestiontype_id' => 2,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:55:50',
            ],
            [
                'id' => 11,
                'titre' => '2. Faiblesses personnelles',
                'position' => '11',
                'diagnosticmodule_id' => 4,
                'diagnosticquestiontype_id' => 2,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 13:50:46',
                'updated_at' => '2025-07-29 13:55:53',
            ],
            [
                'id' => 12,
                'titre' => '3. Opportunités : Ce qui peut t\'aider autour de toi',
                'position' => '12',
                'diagnosticmodule_id' => 4,
                'diagnosticquestiontype_id' => 2,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 13:50:46',
                'updated_at' => '2025-07-29 13:55:56',
            ],
            [
                'id' => 13,
                'titre' => '4. Menaces : Ce qui peut te freiner ou te décourager autour de toi',
                'position' => '13',
                'diagnosticmodule_id' => 4,
                'diagnosticquestiontype_id' => 2,
                'diagnosticquestioncategorie_id' => NULL,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 1,
                'parent' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 13:50:46',
                'updated_at' => '2025-07-29 13:55:21',
            ],
        ]);
    }
}
