<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiagnosticmodulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Vider la table avant d'insérer les nouvelles données
        DB::table('diagnosticmodules')->delete();

        // Insérer les données
        DB::table('diagnosticmodules')->insert([
            [
                'id' => 1,
                'titre' => 'Profil du porteur de projet ou de l\'entrepreneur débutant',
                'position' => 1,
                'description' => '<p>Identifier les forces personnelles, la maturité entrepreneuriale, la résilience émotionnelle, la capacité d\'organisation et la vision stratégique du porteur de projet.</p>',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 1,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => '8409335f-e085-4597-9cae-359a60a816c6',
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 09:50:21',
                'updated_at' => '2025-07-29 13:02:09',
            ],
            [
                'id' => 2,
                'titre' => 'A. Posture entrepreneuriale et soft skills',
                'position' => 1,
                'description' => '<p><br></p>',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 1,
                'parent' => 1,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => '8409335f-e085-4597-9cae-359a60a816c6',
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 13:14:05',
                'updated_at' => '2025-07-29 13:15:29',
            ],
            [
                'id' => 3,
                'titre' => 'B. Intelligence émotionnelle et résilience',
                'position' => 2,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 1,
                'parent' => 1,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => '8409335f-e085-4597-9cae-359a60a816c6',
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 13:15:14',
                'updated_at' => '2025-07-29 13:15:14',
            ],
            [
                'id' => 4,
                'titre' => 'C. Analyse SWOT personnel',
                'position' => 3,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 1,
                'parent' => 1,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => '8409335f-e085-4597-9cae-359a60a816c6',
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-07-29 13:16:38',
                'updated_at' => '2025-07-29 13:16:38',
            ],
            [
                'id' => 5,
                'titre' => 'BLOC 1 – STRUCTURE ORGANISATIONNELLE',
                'position' => 1,
                'description' => NULL,
                'vignette' => 'diagnosticmodules/1767798744_affaire.JPG',
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => '0',
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:12:59',
                'updated_at' => '2026-01-07 15:12:24',
            ],
            [
                'id' => 6,
                'titre' => 'BLOC 2 – MODÈLE ÉCONOMIQUE & VIABILITÉ',
                'position' => 2,
                'description' => NULL,
                'vignette' => 'diagnosticmodules/1767800689_contrat.JPG',
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => '0',
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2026-01-07 15:44:49',
            ],
            [
                'id' => 7,
                'titre' => 'BLOC 3 – GOUVERNANCE & LEADERSHIP',
                'position' => 3,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 8,
                'titre' => 'BLOC 4 – RESSOURCES HUMAINES',
                'position' => 4,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 9,
                'titre' => 'BLOC 5 – CONFORMITÉ LÉGALE, FISCALE ET SOCIALE',
                'position' => 5,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 10,
                'titre' => 'BLOC 6 – GESTION FINANCIÈRE & COMPTABILITÉ',
                'position' => 6,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 11,
                'titre' => 'BLOC 7 – SYSTÈME D\'INFORMATION & DIGITALISATION',
                'position' => 7,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 12,
                'titre' => 'BLOC 8 – STRATÉGIE DE DÉVELOPPEMENT & PARTENARIATS',
                'position' => 8,
                'description' => NULL,
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 2,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 13,
                'titre' => '1️⃣ GOUVERNANCE & VISION STRATÉGIQUE',
                'position' => 1,
                'description' => 'Ce bloc vise à évaluer votre capacité réelle à diriger votre entreprise de manière structurée, avec une vision claire, des objectifs définis et un minimum de pilotage. Il ne s\'agit pas de ce que vous projetez de faire, mais de ce qui est effectivement en place aujourd\'hui dans votre entreprise. Pour chaque question, choisissez la proposition qui décrit le mieux votre situation actuelle.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:40',
                'updated_at' => '2026-01-12 19:57:40',
            ],
            [
                'id' => 14,
                'titre' => '2️⃣ STATUT JURIDIQUE & CONFORMITÉ',
                'position' => 2,
                'description' => 'Ce bloc vise à évaluer le niveau réel de conformité légale, administrative, fiscale et sociale de votre entreprise. Il permet d\'apprécier votre capacité à opérer légalement, à sécuriser vos activités et à accéder sans risque aux marchés, partenariats et financements. Il ne s\'agit pas de vos intentions ou projets futurs, mais de votre situation effective aujourd\'hui.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:40',
                'updated_at' => '2026-01-12 19:57:40',
            ],
            [
                'id' => 15,
                'titre' => '3️⃣ GESTION FINANCIÈRE & COMPTABILITÉ',
                'position' => 3,
                'description' => 'Ce bloc vise à évaluer votre capacité réelle à gérer, suivre et comprendre les finances de votre entreprise. Il permet d\'apprécier si votre entreprise dispose d\'un minimum de discipline financière, condition indispensable pour prendre de bonnes décisions, sécuriser la trésorerie et accéder aux financements. Il ne s\'agit pas de votre chiffre d\'affaires, mais de la qualité de votre organisation financière actuelle.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:40',
                'updated_at' => '2026-01-12 19:57:40',
            ],
            [
                'id' => 16,
                'titre' => '4️⃣ ORGANISATION INTERNE & PROCESSUS',
                'position' => 4,
                'description' => 'Ce bloc permet d\'évaluer le niveau réel d\'organisation interne de votre entreprise : comment le travail est réparti, exécuté, suivi et transmis. Il mesure votre capacité à fonctionner de manière structurée, même en votre absence. Il ne s\'agit pas de votre bonne volonté, mais de la façon dont votre entreprise fonctionne concrètement aujourd\'hui.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
            [
                'id' => 17,
                'titre' => '5️⃣ RESSOURCES HUMAINES & COMPÉTENCES',
                'position' => 5,
                'description' => 'Ce bloc permet d\'évaluer la solidité humaine de votre entreprise : la stabilité de l\'équipe, la clarté des relations de travail, l\'adéquation des compétences et la capacité à faire grandir les personnes. Il ne s\'agit pas du nombre de personnes, mais de la manière dont les ressources humaines sont organisées et développées aujourd\'hui.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
            [
                'id' => 18,
                'titre' => '6️⃣ OFFRE, MARCHÉ & CLIENTS',
                'position' => 6,
                'description' => 'Ce bloc permet d\'évaluer la clarté de votre offre, votre compréhension réelle du marché, et la qualité de votre relation client. Il mesure votre capacité à vendre de façon cohérente, régulière et durable, au-delà des opportunités ponctuelles. Il ne s\'agit pas de ce que vous pensez vendre, mais de ce que vos clients comprennent réellement et achètent aujourd\'hui.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
            [
                'id' => 19,
                'titre' => '7️⃣ CAPACITÉ OPÉRATIONNELLE & EXÉCUTION',
                'position' => 7,
                'description' => 'Ce bloc permet d\'évaluer votre capacité réelle à exécuter ce que vous vendez, à livrer dans les délais, à maintenir la qualité et à faire face aux imprévus. Il mesure si votre entreprise est opérationnellement fiable, au-delà des intentions et des promesses commerciales. Il ne s\'agit pas de ce que vous pensez pouvoir faire, mais de ce que votre entreprise est réellement capable de livrer aujourd\'hui.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
            [
                'id' => 20,
                'titre' => '8️⃣ DIGITALISATION, REPORTING & TRAÇABILITÉ',
                'position' => 8,
                'description' => 'Ce bloc permet d\'évaluer le niveau réel de digitalisation et de traçabilité de votre entreprise : votre capacité à utiliser des outils numériques, à conserver l\'information, à produire des données fiables et à rendre compte de vos activités. Il ne s\'agit pas d\'être \"très digital\", mais de disposer d\'outils simples et réellement utilisés pour mieux gérer l\'entreprise.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
            [
                'id' => 21,
                'titre' => '9️⃣ INFRASTRUCTURES PHYSIQUES',
                'position' => 9,
                'description' => 'Ce bloc permet d\'évaluer la qualité et l\'adéquation de vos infrastructures physiques : bureaux, ateliers, boutiques, équipements et conditions de sécurité. Il mesure si votre cadre de travail est professionnel, rassurant et propice à la croissance de votre entreprise.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
            [
                'id' => 22,
                'titre' => '🔟 RELATIONS AVEC LES TIERS & ÉCOSYSTÈME PROFESSIONNEL',
                'position' => 10,
                'description' => 'Ce bloc vise à apprécier le niveau réel d\'intégration de votre entreprise dans l\'écosystème professionnel formel : conseils juridiques et financiers, prestataires clés, partenaires techniques et financiers, réseaux institutionnels ou professionnels. Il mesure votre capacité à ne pas fonctionner en isolement, à sécuriser vos décisions, et à vous entourer de compétences externes utiles à la pérennité et à la croissance de votre entreprise. Il ne s\'agit pas de contacts occasionnels, mais de relations professionnelles identifiées, utiles et effectivement mobilisées.',
                'vignette' => NULL,
                'diagnosticmoduletype_id' => 3,
                'parent' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'pays_id' => NULL,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2026-01-12 19:57:41',
                'updated_at' => '2026-01-12 19:57:41',
            ],
        ]);
    }
}
