<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiagnosticquestionsModule2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insérer les questions des modules 2 (questions 14-46)
        DB::table('diagnosticquestions')->insert([
            [
                'id' => 14,
                'titre' => 'Est-ce que tu sais clairement "qui fait quoi" dans ton entreprise ?',
                'position' => '1',
                'diagnosticmodule_id' => 5,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:12:59',
                'updated_at' => '2025-08-22 11:12:59',
            ],
            [
                'id' => 15,
                'titre' => 'Est-ce que les rôles et responsabilités sont bien définis ?',
                'position' => '2',
                'diagnosticmodule_id' => 5,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:12:59',
                'updated_at' => '2025-08-22 11:12:59',
            ],
            [
                'id' => 16,
                'titre' => 'Avez-vous des règles ou méthodes de travail bien définies ?',
                'position' => '3',
                'diagnosticmodule_id' => 5,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:12:59',
                'updated_at' => '2025-08-22 11:12:59',
            ],
            [
                'id' => 17,
                'titre' => 'Avez-vous un système pour bien communiquer et vous organiser entre vous ?',
                'position' => '4',
                'diagnosticmodule_id' => 5,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:12:59',
                'updated_at' => '2025-08-22 11:12:59',
            ],
            [
                'id' => 18,
                'titre' => 'Quelle est la valeur réelle que ton offre apporte aux clients ?',
                'position' => '1',
                'diagnosticmodule_id' => 6,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 19,
                'titre' => 'Sais-tu exactement qui est ton client principal ?',
                'position' => '2',
                'diagnosticmodule_id' => 6,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 20,
                'titre' => 'Sais-tu comment ton entreprise gagne de l\'argent ?',
                'position' => '3',
                'diagnosticmodule_id' => 6,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 21,
                'titre' => 'As-tu testé ton activité sur le terrain avant d\'investir beaucoup ?',
                'position' => '4',
                'diagnosticmodule_id' => 6,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 22,
                'titre' => 'Ton modèle peut-il être répété ou développé ailleurs (scalable) ?',
                'position' => '5',
                'diagnosticmodule_id' => 6,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 23,
                'titre' => 'As-tu une vision claire de ce que tu veux bâtir dans 2 à 3 ans ?',
                'position' => '1',
                'diagnosticmodule_id' => 7,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 24,
                'titre' => 'Comment prends-tu les décisions importantes dans ton entreprise ?',
                'position' => '2',
                'diagnosticmodule_id' => 7,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 25,
                'titre' => 'Es-tu accompagné·e ou conseillé·e dans tes décisions stratégiques ?',
                'position' => '3',
                'diagnosticmodule_id' => 7,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 26,
                'titre' => 'Est-ce que tu appliques des valeurs ou principes dans ta façon de gérer ton activité ?',
                'position' => '4',
                'diagnosticmodule_id' => 7,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 27,
                'titre' => 'Comment choisis-tu les personnes qui travaillent avec toi ?',
                'position' => '1',
                'diagnosticmodule_id' => 8,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 28,
                'titre' => 'As-tu rédigé des fiches de poste ou des documents clairs pour expliquer le travail à faire ?',
                'position' => '2',
                'diagnosticmodule_id' => 8,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 29,
                'titre' => 'As-tu une manière de suivre le travail ou d\'évaluer les performances de ceux qui t\'aident ?',
                'position' => '3',
                'diagnosticmodule_id' => 8,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 30,
                'titre' => 'As-tu prévu de former ton équipe ou toi-même pour progresser ?',
                'position' => '4',
                'diagnosticmodule_id' => 8,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 31,
                'titre' => 'Est-ce que ton entreprise est enregistrée officiellement ?',
                'position' => '1',
                'diagnosticmodule_id' => 9,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 32,
                'titre' => 'Est-ce que tu es à jour dans le paiement de tes impôts et taxes ?',
                'position' => '2',
                'diagnosticmodule_id' => 9,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 33,
                'titre' => 'Est-ce que tu as ouvert un compte CNSS pour toi ou ton personnel ?',
                'position' => '3',
                'diagnosticmodule_id' => 9,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 34,
                'titre' => 'Est-ce que tu respectes les règles ou normes propres à ton activité ?',
                'position' => '4',
                'diagnosticmodule_id' => 9,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 35,
                'titre' => 'Est-ce que tu tiens ta comptabilité régulièrement ?',
                'position' => '1',
                'diagnosticmodule_id' => 10,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 36,
                'titre' => 'As-tu une idée claire de tes marges et de ta rentabilité ?',
                'position' => '2',
                'diagnosticmodule_id' => 10,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 37,
                'titre' => 'As-tu un budget prévisionnel ou un plan de trésorerie ?',
                'position' => '3',
                'diagnosticmodule_id' => 10,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 38,
                'titre' => 'As-tu accès à un financement formel (banque, microfinance, subvention…) ?',
                'position' => '4',
                'diagnosticmodule_id' => 10,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 39,
                'titre' => 'Utilises-tu des outils numériques pour gérer ton activité ?',
                'position' => '1',
                'diagnosticmodule_id' => 11,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 40,
                'titre' => 'As-tu une présence en ligne ?',
                'position' => '2',
                'diagnosticmodule_id' => 11,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 41,
                'titre' => 'Utilises-tu des outils de communication digitale avec tes clients ou ton équipe ?',
                'position' => '3',
                'diagnosticmodule_id' => 11,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 42,
                'titre' => 'Tes données (clients, finances, stock…) sont-elles sécurisées et sauvegardées ?',
                'position' => '4',
                'diagnosticmodule_id' => 11,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 43,
                'titre' => 'As-tu un plan pour développer ton activité dans les mois ou années à venir ?',
                'position' => '1',
                'diagnosticmodule_id' => 12,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 44,
                'titre' => 'As-tu des partenaires solides qui t\'aident dans ton développement ?',
                'position' => '2',
                'diagnosticmodule_id' => 12,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 45,
                'titre' => 'Participes-tu à des programmes ou événements qui te permettent de progresser ?',
                'position' => '3',
                'diagnosticmodule_id' => 12,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
            [
                'id' => 46,
                'titre' => 'Est-ce que tu innoves ou fais évoluer ton offre ?',
                'position' => '4',
                'diagnosticmodule_id' => 12,
                'diagnosticquestiontype_id' => 1,
                'diagnosticquestioncategorie_id' => 0,
                'langue_id' => 'f9a16e49-d975-4d63-b201-5aee5888ac44',
                'obligatoire' => 0,
                'parent' => 0,
                'spotlight' => 0,
                'etat' => 1,
                'created_at' => '2025-08-22 11:16:58',
                'updated_at' => '2025-08-22 11:16:58',
            ],
        ]);
    }
}
